[project]
name = "logbook_server"
version = "0.1.0"
description = "A tool to collect and analyse gpx traces."
dependencies = [
    "flask",
    "pymongo>=4.3.2"
]

[build-system]
requires = [
    "flit_core<4",
    "pytest",
    "coverage"
]
build-backend = "flit_core.buildapi"